#!/bin/sh

# update apt
sudo apt-get update

# Install python tools, like curl
sudo apt-get install python-software-properties
sudo apt-get install curl

# Add node PPA
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

# Start to install packages
sudo apt-get install apache2
sudo apt-get install php5
sudo apt-get install libapache2-mod-php5
sudo apt-get install php5-gd php5-sqlite
sudo apt-get install git
sudo apt-get install nodejs
sudo apt-get install build-essential
sudo apt-get install libnotify-bin

# PHP Settings:
sudo chown $USER:$USER /etc/php5/cli/php.ini
sudo echo "always_populate_raw_post_data = -1" >> /etc/php5/cli/php.ini

# Get the git repo
git clone https://github.com/Viva-Resurs/Pixbo.git

# Setup apache
sudo rm -rf /var/www/html
sudo ln -s ~/Pixbo/public /var/www/html


# Install globally needed npm packages
sudo npm install node-gyp@3.3.1 -g

# Install composer
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
sudo composer self-update

# Start Installing the repo
(cd ~/Pixbo && npm install)
(cd ~/Pixbo && composer update --no-scripts)
touch ~/Pixbo/storage/database.sqlite
(cd ~/Pixbo && composer install)
(cd ~/Pixbo && php artisan migrate --seed)

# Set App URL
IP=$(hostname -I | awk '{print $1}')
echo "APP_URL=$IP" >> ~/Pixbo/.env

# Set permissions
sudo chmod 777 -R ~/Pixbo/storage
mkdir -p ~/Pixbo/public/images/screens
sudo chmod 777 ~/Pixbo/public/images/screens

# setup apache
sudo cp ~/Pixbo/pixbo.conf /etc/apache2/sites-available/pixbo.conf
sudo a2dissite 000-default
sudo a2ensite pixbo
sudo a2enmod rewrite
sudo service apache2 reload
sudo service apache2 restart

# cronTab Should look like this: * * * * * /usr/bin/php ~/Pixbo/artisan schedule:run >> /dev/null
croncmd="/usr/bin/php ~/Pixbo/artisan schedule:run >> /dev/null"
cronjob="* * * * * $croncmd"
( crontab -l | grep -v "$croncmd" ; echo "$cronjob" ) | crontab -
